CREATE DATABASE warehouse;

CREATE TABLE IF NOT EXISTS warehouse_products (
   product_id UUID PRIMARY KEY,
   fragile BOOLEAN NOT NULL,
   width DOUBLE PRECISION NOT NULL,
   height DOUBLE PRECISION NOT NULL,
   depth DOUBLE PRECISION NOT NULL,
   weight DOUBLE PRECISION NOT NULL,
   quantity BIGINT NOT NULL CHECK (quantity >= 0),
   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);